# Generated by Django 5.2rc1 on 2025-04-02 16:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('register_no', models.PositiveIntegerField(max_length=9, unique=True)),
                ('sastra_email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=100)),
                ('batch', models.PositiveIntegerField(max_length=4)),
                ('posts', models.CharField(default='[0]', max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=1000000000)),
                ('author_reg_no', models.PositiveIntegerField(max_length=9, unique=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 4, 2, 21, 46, 46, 865918))),
                ('verified', models.BooleanField(default=False)),
                ('verified_by', models.PositiveIntegerField(max_length=9)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.account')),
                ('club_role', models.CharField(max_length=40)),
                ('join_date', models.DateField(default=datetime.datetime(2025, 4, 2, 21, 46, 46, 864918))),
                ('contribution_score', models.FloatField(default=0.0)),
                ('attendance_percentage', models.FloatField(default=0.0)),
            ],
            bases=('website.account', models.Model),
        ),
    ]
